Typo in default files causing Error while cron run
Fixed Following Error due to mistake in config:

 /usr/bin/python /opt/threatelligence/cron/threatelligence_cron.py >/tmp/threatelligence_fetch.log
Traceback (most recent call last):
  File "/opt/threatelligence/bin/ti_fetcher.py", line 66, in <module>
    data_type = Config.get(config_name,'regex_value')
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'regex_value' in section: 'Dragon Research Group - SSH'